# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.TextField(default='a discription'),
            preserve_default=False,
        ),
    ]
